### ISSUE TITLE
Clarify 'core language overview'

### ISSUE THREAD

**Issue by nmushegian** [Kindelia/HVM#104]
https://github.com/Kindelia/HVM/blob/master/HOW.md#hvms-core-language-overview

```
term ::=
  | λvar. term               # a lambda
  | (term term)              # an application
  | (ctr term term ...)      # a constructor
  | num                      # a machine int
  | (op2 term term)          # an operator
  | let var = term; term     # a local definition

rule ::=
  | term = term

file ::= list<rule>
```

The grammar in the link above exacerbates confusion about the issue in the link below:

https://github.com/Kindelia/HVM/issues/64#issuecomment-1030697105

Also, regardless of this syntax issue, isn't the grammar still technically incorrect because for ctr applications you need a `rule`, not just a `term`? Maybe like one of these depending on if you adopt `[]`?

```
  | (term term)              # a lambda application
  | (Rule term)              # a rule application

or

  | (term term)              # a lambda application
  | [rule term]              # a rule application
```

**Comment by quleuber** [comment]
>for ctr applications you need a rule, not just a term

A constructors instantiation is just the name of the constructor followed by some terms. It doesn't need to be a "rule" at all. `(Foobar)` is a constructor even if there's no rule with `(Foobar)` on the left side. Example:

```
(Foo (Bar x)) = x

(Main) = 
  let v = (Bar 11)
  (Foo v)
  // returns 11
```

`(Bar 11)` is still a term/expression, even though we don't have a `Bar` rule.

This is also valid.
```
(Main) = (Crab)
```

---

```
  | (term term)              # a lambda application
  | (Ctr term term ...)    # a constructor instantiation
```
I think using the above would be a bit more clear.

Or specifying separately what `var`, `ctr`, `op` etc are.

**Comment by nmushegian** [comment]
Understood, I think you have a good sense of what needs to be clarified so I'll just close this bc it's directionless
