### ISSUE TITLE
Program gives different outputs if interpreted or compiled

### ISSUE THREAD

**Issue by judomat** [Kindelia/HVM#116]
When I run this program
```
(Append_2 Nil ys) = ys
(Append_2 (Cons x xs) ys) = let b = (Cons x xs); (Cons x (Append_2 xs ys))

(Main) = (Append_2 (Cons 0 (Cons 1 (Cons 2 (Nil)))) (Cons 0 (Cons 1 (Cons 2 (Nil)))))
```
with the latest version of hvm on master the output is
```
[0, 1, 2, 0, 1, 2]
```
in interpreted mode which makes a lot of sense.
But if I try to compile it I get
```
(Nil)
```
And if I change the program to
```
(Append_2 Nil ys) = ys
(Append_2 (Cons x xs) ys) = let b = (Cons x Nil); (Cons x (Append_2 xs ys))

(Main) = (Append_2 (Cons 0 (Cons 1 (Cons 2 (Nil)))) (Cons 0 (Cons 1 (Cons 2 (Nil)))))
```
I get the right result both in interpreted mode and compiled. What is going on? The two programs are equivalent I shouldn't get different outputs...

**Comment by lawcho** [comment]
Here is a reduced test case:

```hvm
(Last Nil) = Error
(Last (Cons x Nil)) = x
(Last (Cons x xs)) = let b = xs; (Last xs)

Main = (Last (Cons 0 (Cons 1 (Cons 2 (Nil)))))
```

Breaks with the compiler (even with `--single-thread`, so probably unrelated to #119):

```bash
$ hvm c tests/debug.hvm --single-thread && gcc tests/debug.c && ./a.out 
Compiled to 'tests/debug.c'.
(Cons 1 (Cons 2 (Nil)))

Rewrites: 8 (0.00 MR/s).
Mem.Size: 16 words.
```

Reduces OK with the interpreter:

```bash
$ hvm r tests/debug.hvm 
2

Rewrites: 14 (inf MR/s)
Mem.Size: 25
```

Removing the `let b = xs` also fixes the program.

Tested on current `master`, commit `0bcbae286f995bc14895b0774914b1e19cf5e34e`

**Comment by VictorTaelin** [comment]
Fortunately the C target is being replaced by a Rust only compiled runtime, so this will be solved on the upcoming version (around next month), together with the correct parallel version and hopefully a GPU target.

**Comment by VictorTaelin** [comment]
We now compile to Rust, so this should be fixed on Master!
