### ISSUE TITLE
Consider publishing `src/parser.rs` under separate Cargo crate

### ISSUE THREAD

**Issue by FranchuFranchu** [Kindelia/HVM#127]
`src/parser.rs`'s code is mostly independent from HVM now. I think it's a really nice parser to use in general and would love to see it published under a separate crate to encourage other people to use it without them having to care about HVM (or having to copy-paste the code into their own projects).

Thanks to the MIT license I could obviously do this myself and become the maintainer of the parser, but that seems a bit silly since I never even contributed to the parser and am completely unrelated to the HVM project. That is why I am asking here if the HVM developers want to do it themselves.

**Comment by steinerkelvin** [comment]
I think this is nice. I was already thinking about doing it for Kind2 (but generating the parser with Tree-sitter). It would help to compile and use the parser independently on the browser, for example.
I just need the time. 😅

**Comment by VictorTaelin** [comment]
It isn't that nice of a parser though, but it is indeed independent so yes, may be a good idea.

**Comment by VictorTaelin** [comment]
Closing the issue, but I intend to do it later on.
