### ISSUE TITLE
How does HVM decide on the order of reduction operations?

### ISSUE THREAD

**Issue by danaugrs** [Kindelia/HVM#129]
For example:
```js
// List Map function
(Map f Nil)         = Nil
(Map f (Cons x xs)) = (Cons (f x) (Map f xs))

// List projectors
(Head (Cons x xs)) = x
(Tail (Cons x xs)) = xs

// The infinite list: 0, 1, 2, 3 ...
Nats = (Cons 0 (Map λx(+ x 1) Nats))

// Just a test (returns 2)
Main = (Head (Tail (Tail Nats)))
```
Let's reduce `Main`:
```js
Main = (Head (Tail (Tail Nats))) // start
    Main = (Head (Tail (Tail (Cons 0 (Map λx(+ x 1) Nats))))) // reduced Nats
        Main = (Head (Tail (Tail (Cons 0 (Map λx(+ x 1) (Cons 0 (Map λx(+ x 1) Nats))))))) // reduced Nats
            // ... (can keep reducing Nats infinitely)
        Main = (Head (Tail (Tail (Cons 0 (Cons (λx(+ x 1) x) (Map λx(+ x 1) Nats)))))) // reduced Map
            // ...
        Main = (Head (Tail (Map λx(+ x 1) Nats))) // reduced Tail
            // ...
```
The first reduction has to be `Nats`, but after that HVM can choose between `Nats`, `Map`, and `Tail`. How does it choose?

**Comment by steinerkelvin** [comment]
You may find the command `hvm debug` useful. Here is the the output for your code:

[debug.txt](https://github.com/Kindelia/HVM/files/9020267/debug.txt)

https://termbin.com/9g4s

**Comment by danaugrs** [comment]
That's great, thanks!

**Comment by danaugrs** [comment]
Saw a formalization of this [here](https://www.researchgate.net/profile/David-Lester-4/publication/228377970_Implementing_functional_languages_a_tutorial/links/02bfe51041cede4142000000/Implementing-functional-languages-a-tutorial.pdf) (page 43).

A reduction algorithm that always picks the outermost reducible expression (redex) to reduce always terminates if termination is possible. Looks like HVM does it this way as well.

> At any time there may be more than one redex in the expression being evaluated, so there is a choice about which one to reduce next. Fortunately, whatever reduction sequence we choose, we will always get the same answer (that is, normal form). There is one caveat: some reduction sequences may fail to terminate. However, if any choice of redexes makes evaluation terminate, then the policy of always selecting the outermost redex will also do so. This choice of reduction order is called normal order reduction, and it is the one we will always use.
