### ISSUE TITLE
Support for rudimentary C FFI/string processing utils?

### ISSUE THREAD

**Issue by Sintrastes** [Kindelia/HVM#132]
Apologize if this has been answered somewhere else.

Are there any plans for adding a rudimentary C FFI to this project? I'm really interested in how a simple breadth-first search implementation of a simple logic programming language (like [this one](https://github.com/kfl/pure-prolog)) would preform on the HVM -- and if it works out well, to actually use it as a compilation target.

It seems to me that in order to even get some reasonable benchmarks for something like this on the HVM, I'd need to either use some kind of FFI, or use the native string processing utilities built into HVM (which I'm not sure if there are any) to implement a parser for the facts and rules that would be used to build up a (possibly infinite) search tree.

Are any of these things possible, or planned for the future? Would be really interested to try something like this out, but I'm not sure how many roadblocks I'd run into trying to do something like this with the project as-is.

**Comment by VictorTaelin** [comment]
FFI isn't planned, but could be a good addition. I wonder it would look like in a pure language like HVM. I think it would be hard to design one that doesn't pollute the code, or end up being a long-term burden. How would the syntax look like?

**Comment by VictorTaelin** [comment]
The way we're doing IO is:

1. We have a bunch of built-in IO operations (file write/read, logging, etc.)

2. We let users add more IOs by writing a new rewrite rule in Rust

More info on the guide.
