### ISSUE TITLE
`malloc(HEAP_SIZE)` fails, compiled programs crash

### ISSUE THREAD

**Issue by lawcho** [Kindelia/HVM#140]
On my system (`x86_64 Clear Linux OS`), `hvm r` runs OK, but  `hvm c` produces code which crashes every time.

The error is always something like:
```a.out: fibonacci.c:1566: main: Assertion `mem.node' failed.```

If we look at `fibonacci.c`, line 1566 is this assert statement:

```
  mem.size = 0;
  mem.node = (u64*)malloc(HEAP_SIZE);
  mem.aris = id_to_arity_data;
  mem.funs = id_to_arity_size;
  assert(mem.node);
```

`prinf`-debugging shows that `malloc` is passed the full size of my RAM, and returns `(nil)`

I don't know what a good long-term fix would be, but replacing `HEAP_SIZE` with `HEAP_SIZE/2` worked this time.

**Comment by lawcho** [comment]
This seems to be a come-back of issue #35

**Comment by VictorTaelin** [comment]
I believe we do not have a command-line argument for setting a memory size on the generated C file, so you'd have to edit the generated `fibonacci.c` file to use less memory, by replacing `#define HEAP_SIZE (8 * U64_PER_GB * sizeof(u64))` by a smaller number (like 2 or 4, depending on how much memory you have). We're working on a smarter allocator right now!

**Comment by lawcho** [comment]
You can now avoid this by setting the heap size at compile-time, e.g: `hvm -M 2k compile fibonacci.c`
