### ISSUE TITLE
Confused by testing infrastructure

### ISSUE THREAD

**Issue by lawcho** [Kindelia/HVM#143]
What is the go-to testing command supposed to be?

* `cargo test` crashes (`memory allocation of 34359738368 bytes failed`)
  * fixed in #157
* `cd bench; ./bench/test.sh` prints lots of `XXX FAILED XXX` (and hides the errors)
* `python3 tests/test_cli.py` runs the tests in `test/` (most pass, given the right options)

**Comment by VictorTaelin** [comment]
@steinerkelvin @racs4

**Comment by VictorTaelin** [comment]
I'll add a new testing infra soon. Closing for now.
