### ISSUE TITLE
Useless `let` produced by rule sanitization

### ISSUE THREAD

**Issue by developedby** [Kindelia/HVM#154]
While writing a test for the rule flattening algorithm, I noticed something strange.
I was flattening this rule `(A (B 2) 1) = 9`, and I expected it to generate these two rules:
```
(A (B .1) 1) = (A.0 .1)
(A.0 2) = 9
```
Instead, it created
```
(A (B x0) 1) = let x0.0 = x0; (A.0 x0.0)
(A.0 2) = 9
```
Different variable names aside, there is no need for the rule sanitization to insert a `let` expression here.

**Comment by VictorTaelin** [comment]
It is just an artifact of the algorithm that includes `dups` IIRC. Has no effect on the generated runtime memory since lets (after deduplication) just redirect pointers. So I don't think there is a need to change that internal behavior, unless you mean it actually changes the resulting program?

**Comment by developedby** [comment]
I don't think it changes anything, it was just unexpected since it doesn't add anything either.
