### ISSUE TITLE
Guide is outdated

### ISSUE THREAD

**Issue by divs1210** [Kindelia/HVM#171]
Hi!

I'm running HVM version 0.1.89.

I was following the guide to give HVM a spin, but ran into some issues:

1. `hvm run "(Expression)"` command doesn't work anymore, it needs a filename as an argument instead of an expression
2. `HVM.query` isn't working - it doesn't wait for user input, just assumes nil. This is regarding the following code example:

```
(String.concat String.nil         ys) = ys
(String.concat (String.cons x xs) ys) = (String.cons x (String.concat xs ys))

Main =
  (HVM.print "What is your name?"
             (HVM.query @name(HVM.print (String.concat "Hello, " name)
                                        (Done))))
```

**Comment by VictorTaelin** [comment]
It is actually the other way around, you're probably using the old version, since the latest wasn't published on Cargo. Type `cargo install hvm` again and it should work now. Current version is `1.0.0-beta`. We'll release 1.0.0 soon.

**Comment by divs1210** [comment]
Hmm. 

I have 0.1.89 installed, and running `cargo install hvm` made no change.

Then I ran `cargo install hvm --version 1.0.0-beta` but that gave me the following errors:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/hvm-1.0.0-beta/src/lib.rs:1:12
  |
1 | #![feature(atomic_from_mut)]
  |            ^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/hvm-1.0.0-beta/src/lib.rs:2:12
  |
2 | #![feature(atomic_mut_ptr)]
  |            ^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `hvm` due to 2 previous errors
error: failed to compile `hvm v1.0.0-beta`, intermediate artifacts can be found at `/var/folders/86/0m74r2xn4yz74znbcwgp85gr0000gp/T/cargo-install7kYuMp`
```

**Comment by zicklag** [comment]
@divs1210 you should be able to install it like this:

```
rustup install nightly
cargo +nightly install --force --git https://github.com/Kindelia/HVM.git
```

The first command installs the nightly Rust distribution, which it looks like HVM requires for now, and then the second command installs the latest version from the git repo.

**Comment by VictorTaelin** [comment]
I guess my install instructions are wrong, sorry. Can someone update on the README and on guide/README and PR please?

**Comment by zicklag** [comment]
Yeah, I'll open a PR soon.

Your instructions weren't really wrong for a first-time setup: you did say to set Rust nightly as the default, but it's easy to miss that step or set it back to stable for a different project or something like that.

Otherwise using `--force` and `--git` just makes sure it works in more scenarios, if you already have it installed or have an out-of-date git clone.

**Comment by divs1210** [comment]
Thank you, @zicklag!
That worked. 🙂

**Comment by HenkPoley** [comment]
Just a little reminder that the project README.md still tells people to install the 3 month old (broken?) stable version; and set their default rust toolchain to nightly instead of use `cargo +nightly install`: https://github.com/Kindelia/HVM/blob/4974a8ae7c83b775aaf627719e638d06dac4a4dc/README.md#getting-started

**Comment by VictorTaelin** [comment]
@racs4 this was fixed, right? Can we close this issue?

**Comment by racs4** [comment]
My PR #192 with the new instructions was not accepted

**Comment by HenkPoley** [comment]
Maybe merge #205 as well.

It appears `-c` now needs to be `-c true`.
