### ISSUE TITLE
Attempting to `cargo install --path .` for the Summation.hvm example from the HVM guide readme fails

### ISSUE THREAD

**Issue by bishboria** [Kindelia/HVM#185]
I followed the installation instructions in HVM/guide/README.md, and created the summation.hvm file.

In the Compiling A Program section, when trying to run `cargo install --path .` I get the following errors:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:1:12
  |
1 | #![feature(atomic_from_mut)]
  |            ^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:2:12
  |
2 | #![feature(atomic_mut_ptr)]
  |            ^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
```

I'm currently running `hvm 1.0.13-beta`, and *did* use the nightly options when setting up rust and cargo.
My OS: MacOS 12.6.1.

**Comment by nothingnesses** [comment]
I also had this problem and got around it by using [a "rust-toolchain.toml" file with these contents](https://github.com/nothingnesses/LambdaVM-Rust/blob/371dd9258bd3c6c69c99d8b54839c2baf64c71c3/rust-toolchain.toml) in the root of the project. Maybe see if it work for you as well?

**Comment by nothingnesses** [comment]
I created a PR that should address this, please feel free to try it and confirm if it works for you.

**Comment by bishboria** [comment]
I uninstalled the old set up to start fresh. Where does cargo put the HVM repo? I need to check out the PR branch and try it out :)

**Comment by zicklag** [comment]
@bishboria you should be able to install HVM from @nothingnesses's fork like this:

    cargo +nightly install --git https://github.com/nothingnesses/LambdaVM-Rust.git --branch jia/#185

**Comment by bishboria** [comment]
@zicklag Thanks.

Can confirm that @nothingnesses' PR works. Cheers!
