### ISSUE TITLE
Generated C code runs forever

### ISSUE THREAD

**Issue by nothingnesses** [Kindelia/HVM#19]
@VictorTaelin

> Just to be sure, all works fine there?

Hmm, I'm actually not sure. I tried one of the benchmarks which ended up compiling ok, with only the following warning:

```
bash-5.1$ clang -O2 compose_id.hovm.out.c -o main -lpthread
compose_id.hovm.out.c:974:23: warning: incompatible pointer to integer conversion assigning to 'Thd' (aka 'unsigned long') from 'void *'
      [-Wint-conversion]
    workers[t].thread = NULL;
                      ^ ~~~~
1 warning generated.
```

But when I try to run the resulting binary, it doesn't seem to finish running, instead seemingly getting stuck:

```
bash-5.1$ ./main
Reducing.

```

It hasn't printed anything after that new line for > than 30 minutes (I ended up killing it). Not sure if it's actually not working properly or if it's just my slow CPU though. When I looked at my process manager, the process didn't seem to be using any CPU cycles either.

> What is your CPU

```
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         40 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               AuthenticAMD
  Model name:            HP Hexa-Core 2.0GHz
    CPU family:          22
    Model:               48
    Thread(s) per core:  1
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            1
    Frequency boost:     enabled
    CPU max MHz:         2000.0000
    CPU min MHz:         1000.0000
    BogoMIPS:            3992.48
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_op
                         t pdpe1gb rdtscp lm constant_tsc rep_good acc_power nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3
                         cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefet
                         ch osvw ibs skinit wdt topoext perfctr_nb bpext ptsc perfctr_llc cpb hw_pstate ssbd vmmcall bmi1 xsaveopt arat npt lbrv svm_lo
                         ck nrip_save tsc_scale flushbyasid decodeassists pausefilter pfthreshold overflow_recov
Virtualization features:
  Virtualization:        AMD-V
Caches (sum of all):
  L1d:                   128 KiB (4 instances)
  L1i:                   128 KiB (4 instances)
  L2:                    2 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Full AMD retpoline, STIBP disabled, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

_Originally posted by @nothingnesses in https://github.com/Kindelia/HOVM/issues/15#issuecomment-1021494829_

**Comment by quleuber** [comment]
Which benchmark are you running?

That warning should not affect the result, but I'll fix it anyway. It's something that only shows on Linux for some reason.

**Comment by nothingnesses** [comment]
@quleuber The benchmark I initially tried to run no longer exists in the repo (it used to be [this one](https://github.com/Kindelia/HOVM/blob/22b0019448ea74e046a1c3810ffb330906c7bb79/bench/Composition/compose_id.hovm)), but I also recently tried compiling and running the "BinaryTreeSum", "Composition" and "Fibonacci" benchmarks which all get stuck [as of this commit](https://github.com/Kindelia/HOVM/commit/0a88ccd13d1d29bf0897236ef47afd32b6af4eae). I'm currently trying to debug the output C code from the "Fibonacci" benchmark (built with `clang -lpthread -g -O0 main.hovm.out.c -o main` to enable debug symbols), but it's going slowly so far. I'll let you know if I make any progress.

**Comment by quleuber** [comment]
I just thought that maybe this is due to some `pthread` API misuse.

Then I got this from running `valgrind --tool=helgrind ./main` :

```
==1761== Possible data race during read of size 1 at 0x81114D8 by thread #1
==1761== Locks held: none
==1761==    at 0x895977C: ??? (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==1761==    by 0x8959A2A: ??? (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==1761==    by 0x10D4B2: ffi_normal (main.hovm.out.c:1046)
==1761==    by 0x10E4DD: main (main.hovm.out.c:1307)
==1761==  Address 0x81114d8 is 1048 bytes inside data symbol "workers"
==1761==
==1761== ----------------------------------------------------------------
==1761==
==1761== Thread #1's call to pthread_mutex_destroy failed
==1761==    with error code 16 (EBUSY: Device or resource busy)
==1761==    at 0x8959B43: ??? (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==1761==    by 0x10D4B2: ffi_normal (main.hovm.out.c:1046)
==1761==    by 0x10E4DD: main (main.hovm.out.c:1307)
==1761==
==1761== ----------------------------------------------------------------
==1761==
==1761== Thread #1: pthread_cond_destroy: destruction of condition variable being waited upon
==1761==    at 0x895A953: ??? (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==1761==    by 0x10D4D0: ffi_normal (main.hovm.out.c:1047)
==1761==    by 0x10E4DD: main (main.hovm.out.c:1307)
```

**Comment by VictorTaelin** [comment]
Is it because you'er not supplying arguments? The benchmarks now require you to call them with the `n` parameter, like `./main 10`. Regardless, it shouldn't loop if you don't. What command are you using?

**Comment by nothingnesses** [comment]
@VictorTaelin Those results were from before the benchmark programs were changed to be parameterised. I'll try compiling and running them (or at least the Fibonacci benchmark) again using the latest commit to see if there's any change, and I'll update you on the new results when I get them.

**Comment by VictorTaelin** [comment]
I see. I think the main priority for the project now is to make sure it room smoothly on all platforms. Here it works fine, though:

```
v@v ~/vic/dev/Kindelia/HVM/bench/Fibonacci$ hvm c main.hvm
Compiled to 'main.c'.
v@v ~/vic/dev/Kindelia/HVM/bench/Fibonacci$ clang -O2 main.c -o main -lpthread
v@v ~/vic/dev/Kindelia/HVM/bench/Fibonacci$ time ./main 10
Rewrites: 530 (0.02 MR/s).
Mem.Size: 123 words.

55
./main 10  0.01s user 0.02s system 6% cpu 0.528 total
```

I wonder how I can debug an issue that doesn't happen on my computer? That kind of problem sucks.

**Comment by quleuber** [comment]
@VictorTaelin I also reproduced the bug on Linux before that change.

**Comment by VictorTaelin** [comment]
@quleuber can you give me access to that machine?

**Comment by VictorTaelin** [comment]
@nothingnesses does it work if you edit the `c` file and remove the `#define PARALLEL` line?

**Comment by quleuber** [comment]
Oh, I forgot to say that. It works without `#define PARALLEL`.

**Comment by nothingnesses** [comment]
@VictorTaelin Ah yes, it works without that line!

**Comment by nothingnesses** [comment]
@VictorTaelin Now I get a segfault with commit 629e4accb4bd0c5b022ea97fcb39a1283a3623f9:
```
$ git rev-parse HEAD
629e4accb4bd0c5b022ea97fcb39a1283a3623f9
$ nix --extra-experimental-features nix-command --extra-experimental-features flakes develop
bash-5.1$ nix --extra-experimental-features nix-command --extra-experimental-features flakes build
bash-5.1$ cd bench/Fibonacci
bash-5.1$ ../../result/bin/hvm compile main.hvm
Compiled to 'main.c'.
bash-5.1$ clang -O2 main.c -o main -lpthread
bash-5.1$ time ./main 10
Segmentation fault

real	0m0.245s
user	0m0.096s
sys	0m0.143s
bash-5.1$
```

**Comment by nothingnesses** [comment]
@quleuber Works now, thanks!
