### ISSUE TITLE
Binary compiled from generated C fails to allocate memory

### ISSUE THREAD

**Issue by nothingnesses** [Kindelia/HVM#35]
### Reproduction
```
$ git rev-parse HEAD
ff9ed47b163d6d24fdc6f968d35b95b81deb0969
$ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
$ cd bench/Fibonacci
$ ../../target/debug/hvm c main.hvm
Compiled to 'main.c'.
$ clang -g -O2 main.c -o main -lpthread
$ ./main 10
main: main.c:1337: int main(int, char **): Assertion `mem.node' failed.
Aborted
$
```

The message is from:
https://github.com/Kindelia/HVM/blob/ff9ed47b163d6d24fdc6f968d35b95b81deb0969/src/runtime.c#L1229
But I think the change in 99e32862b76c92490cf968c82ecda807155f2fdb is ultimately what's causing it.

**Comment by VictorTaelin** [comment]
Does it work with 8GB in your machine? I'm really confused now; anyone has an idea why exactly that is happening? Ideally we should not alloc surge a large space and just improve the allocator to grow dynamically, but I thought that would not be a problem initially.

**Comment by nothingnesses** [comment]
Yes, I can confirm that it works again as of your 1e31079ef9f0d656b021f645e0dd59f24b59a2ff commit.

**Comment by VictorTaelin** [comment]
Sad! The allocator needs improvements

**Comment by lawcho** [comment]
The commit 1e31079ef9f0d656b021f645e0dd59f24b59a2ff (HVM 0.1.0) didn't fix this for me.
