### ISSUE TITLE
README time complexity wording

### ISSUE THREAD

**Issue by Jlobblet** [Kindelia/HVM#40]
To quote from the README as of b95388f5a5a098946df377d428b122b976be70b1:

> This chart isn't wrong: HVM is *exponentially* faster for function composition, due to optimality, depending on the target function. There is no parallelism involved here. In general, if the composition of a function `f` has a constant-size normal form, then `f^(2^N)(x)` is **constant-time (`O(N)`)** on HVM, and exponential-time (`O(2^N)`) on GHC. This can be taken advantage of to design novel functional algorithms. I highly encourage you to try composing different functions and watching how their complexity behaves. Can you tell if it will be linear or exponential? Or how recursion will affect it? That's a very insightful experience!

The bolded section of text (**constant-time (`O(N)`)**) doesn't make sense - I think it's meant to say linear time.

**Comment by VictorTaelin** [comment]
Oops, that's correct. Thank you.
