### ISSUE TITLE
Typo in HOW.md

### ISSUE THREAD

**Issue by WorldSEnder** [Kindelia/HVM#42]
https://github.com/Kindelia/HVM/blob/14a02de71bd244247abc12749bbc37461feee33d/HOW.md?plain=1#L572

When introducing Dup-Sup, at one point you use the old notation for superposition (`<r s>`), but everywhere else the other style is used. This should read `dup a b = {r s}` if I'm not mistaken.

**Comment by VictorTaelin** [comment]
You're right. Can someone PR a fix?

**Comment by racs4** [comment]
Fixed in 05ad74f
