### ISSUE TITLE
Add Binary format?

### ISSUE THREAD

**Issue by slightknack** [Kindelia/HVM#43]
In the same vein as Wasm, adding a simple binary format might make HVM an easier/more compact target for language backends. Startup times may also be faster, as there's no need to parse unicode and build up the syntax tree. Thoughts?

---

As an aside, are you planning on documenting a public interface and releasing on crates.io for use in other Rust projects?

**Comment by VictorTaelin** [comment]
Yes for both. All should be done.

**Comment by iMplode-nZ** [comment]
Yeah, I'd really like if HVM was bytecode with a frontend that looks like the current.
