### ISSUE TITLE
`runtime.c` template as valid C file

### ISSUE THREAD

**Issue by quleuber** [Kindelia/HVM#53]
Right now the `src/runtime.c` template is not a valid C file before the substitutions are made. This hardens developing on that file unnecessarily.

Some solutions to this are discussed on #32, e.g.

> Sure, or variations of int value = /* START */ 0 /* END */; expressions where it is important, and replace both tokens and the content they box.

**Comment by VictorTaelin** [comment]
That's clever.

**Comment by cauefcr** [comment]
https://github.com/Kindelia/HVM/pull/68 🙏

**Comment by quleuber** [comment]
Fixed by 
e08f17e91cba65f9a94d0bbbc3365b0c7dd2c264
a9bb0ff0797301d85788034a2cc74ee8c153ffa0
