### ISSUE TITLE
Thread-safe synchronization of dup-related rewrite rules

### ISSUE THREAD

**Issue by VictorTaelin** [Kindelia/HVM#66]
The following program:

```
(Sum Nil        ) = 0
(Sum (Cons x xs)) = (+ x (Sum xs))

(Mul Nil        ) = 1
(Mul (Cons x xs)) = (* x (Mul xs))

(Main x) =
  let xs = (Cons 1 (Cons 2 (Cons 3 Nil)))
  (Pair (Sum xs) (Mul xs))
```

Sometimes gives the wrong result when evaluated in parallel, due to synchronization of dup nodes. As I mention on [HOW.md](https://github.com/Kindelia/HVM/blob/master/HOW.md), the fact values exist only at one place greatly simplifies parallelism, and most rewrite rules are thread-safe by design, since the thread has full ownership of every memory location it reads/writes to. There is an exception to that rule, though: dup nodes. For example, consider the program below:

```
dup a b = (Cons 1 (Cons 2 (Cons 3 Nil))))
...
```

It **can** happen that two different threads arrive at the same dup node (which is impossible for all other nodes): one coming from the `a` binder, and other coming from the `b` binder. This will case both threads to attempt to apply the `DUP-CTR` rule at the same time, which may result in errors. To avoid this issue, we must make sure that, whenever a thread accesses a dup node from one of its binders (either `a` or `b` here), it locks the area, preventing outside threads from accessing it. This was (naively) prevented by using `atomic_inc` as a lock [here](https://github.com/Kindelia/HVM/blob/master/src/runtime.c#L468), but this is a temporary solution, which was expected to break in some cases, as depicted above. A more robust solution must be carefully designed to ensure that two threads won't access the same dup node at the same time; i.e., once a thread accesses a dup node, it must lock any subsequent access to it, and a thread that attempts to do so must spinlock until the other is done.

**Comment by brianmingus3** [comment]
What about a lookup table; instead of spinlocking it references the future value, which is substituted later.

**Comment by brianmingus3** [comment]
Apologies if I am not understanding this correctly; is this an opportunity to introduce lazy computation via `std::future`?

**Comment by brianmingus3** [comment]
To be valid C++, `static_cast` must be used for malloc/realloc, and `strdup` can be used:

![image](https://user-images.githubusercontent.com/94937429/152922952-0cb541cd-3d82-4df8-a7c5-7e4bbdb12a10.png)

**Comment by VictorTaelin** [comment]
I don't understand what you're trying to propose, sorry. std::future has nothing to do with this problem, it is a matter of using atomics/locks in the right places.

**Comment by sgraf812** [comment]
From what I understand, this issue sounds related to what GHC's RTS calls "blackholing". This SO answer seems like a good introduction: https://stackoverflow.com/a/31974133/388010.

Well, probably more in that "once you properly synchronise access to `dup` nodes (however that works), you might see that it's not so harmful to do some `dup`ped RHSs more than once".

**Comment by VictorTaelin** [comment]
Yes, that looks like the exact same situation, translated to HVM realm. Nice catch. And yes, the solution *could* be to "just dup twice", but that would still require a properly thought use of atomics to let it happen without two threads tripping on each other.

**Comment by VictorTaelin** [comment]
Closing, since the new parallel runtime performs atomic duplications and substitutions.
