### ISSUE TITLE
More numeric types

### ISSUE THREAD

**Issue by steinerkelvin** [Kindelia/HVM#81]
> > Right now, HVM only supports U32. The numeric types above should be supported too. I32 and F32 should be easy to add, since they are unboxed, like U32. I64, U64 and F64 require implementing boxed numbers, since they don't fit inside a 64-bit Lnk (due to the 4-bit pointer), but shouldn't be hard. Discussion on whether we should have unboxed 60-bit variants is valid.
> 
> I'd be interested in adding support for at least the unboxed numeric types as this seems like a low hanging fruit. I just wanted to check what the concensus was between implicit/explicit casting and how operators should function in regards to mixed input types. My instinct would just be to cast up to the 'bigger' type but maybe operators should only operate on the same type - combined with explicit casts. 
> @VictorTaelin what do you think?

_Originally posted by @samtoth in https://github.com/Kindelia/HVM/issues/38#issuecomment-1037127813_

---

- [ ] unboxed
  - [ ] integer: `I32`
  - [ ] float: `F32`
- [ ] boxed
  - [ ] integer: `U64`, `I64`
  - [ ] float: `F64`

**Comment by VictorTaelin** [comment]
F60 and U60 are now merged on Master. I don't think we should have other integer types.

**Comment by Janiczek** [comment]
@VictorTaelin Can you comment on / give links to some papers on how to lower signed integers (in higher-level languages) to unsigned integers (in HVM as a backend)? It's not immediately obvious to me.

**Comment by VictorTaelin** [comment]
Hmm perhaps adding `Int` isn't a bad idea to be fair. Should be very simple to do now (see F60.hvm and U60.hvm).

**Comment by zicklag** [comment]
Do we have f32 and i32 already?

**Comment by VictorTaelin** [comment]
No, I think f32/i32/u32 should just be implemented as a lib, but not too sure about that. Any reason you think these should be native? I believe a minimalist design is important, must have caution not to become a bloated spec

**Comment by zicklag** [comment]
If f32/i32/u32 can be implemented as a lib without performance issues I'm totally fine with it. I was just thinking about use-cases for games where f32's are used heavily. I'd assume we'd want to be able to take advantage of hardware float operations, which I wasn't sure if we could do in a lib or not.

**Comment by VictorTaelin** [comment]
In that case you should just use a F60. Since the pointer size is 64, a F32 would just have 28 empty bits. What we could (should?) do in a future perhaps is have a 32-bit version of HVM?

**Comment by zicklag** [comment]
That's an interesting question. I'm not sure if using 64 bit floats everywhere would have negative impact on performance or not.

Maybe a 32-bit HVM does make sense. I don't know. 🤷‍♂️
