### ISSUE TITLE
Crazy idea: team with SimulaVR to make next-gen UX

### ISSUE THREAD

**Issue by dumblob** [Kindelia/HVM#84]
I've just noticed the recently "kickstartered" [SimulaVR](https://simulavr.com/ ) "virtual reality computer". Which is cool on its own, but what's cooler is the UX software is written in Haskell.

They seem to plan to make a second version of the SW which they still seem to contemplate the design & workings of. Wouldn't it be cool to write this next gen UX SW in something which targets HVM (e.g. Kind)?

It didn't seem to me there is extreme pressure for the next gen version which should rather be based on the experience & usage data gathered from the current version which on its own will take months at least.

@georgewsinger if you find some time, feel free to chime in here :wink:.

**Comment by VictorTaelin** [comment]
Not sure if I get, but building nice UXs in HVM would, beforehand, need a way to build nice UXs on Rust, right? So we can do the pumbling. What is the currently used Rust -> Web App thing?

**Comment by nothingnesses** [comment]
[Tauri](https://github.com/tauri-apps/tauri)? Or are you talking about the [various front-end frameworks](https://www.arewewebyet.org/topics/frameworks/#pkg-iced) in existence?

**Comment by bjm5** [comment]
A quick evaluation of SimulaVR suggests it needs several - 10? - processor generations to become viable.

**Comment by iMplode-nZ** [comment]
Why? VR is viable right now already for some games so I don't see why this would need more processor power.

**Comment by bjm5** [comment]
It has poor ergonomics.
