### ISSUE TITLE
HVM eats all my RAM and then segfaults

### ISSUE THREAD

**Issue by mb64** [Kindelia/HVM#85]
[Here's a lambda term](https://github.com/mb64/LC-interpreter/blob/main/bench.lc) I have used in the past as a benchmark for my own lambda calculus interpreter.  My interpreter runs it in 3.5s, GHC runs it in 2.5s, and neither goes past the minimum heap size of a few megabytes.

When I run it in HVM, it gradually allocates more and more memory, finishing up with around 8.5 GB and then segfaulting.

Steps to reproduce:
```shell
$ cat > bench.hvm <<EOF
// Computes 0 by subtracting a number from itself    
Main = ((λbig λsub (sub big big))
  // the big number, 43'046'721
  ((λs λz (s(s(s(s z))))) (λs λz (s(s z))) (λs λz (s(s(s z)))))
  // the subtraction algorithm
  (λn λm λs λz
    (n (λy λk (k (s (y (λa λb a))) y))
       (λk (k z (λ_ z)))
       (m (λk λa λb (b k)) (λa λb a)))))
EOF
$ cargo run -- c bench.hvm
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/hvm c bench.hvm`
Compiled to 'bench.c'.
$ gcc -o test -pthread -O2 bench.c
$ ./test
Segmentation fault (core dumped)
```

**Comment by LeoRiether** [comment]
I ran some tests measuring the number of rewrites HVM does to compute `(sub big big)` using [this script](https://gist.github.com/LeoRiether/ba6431429b976b6f814e12f594fca4c3) and got this:

<details>
<summary>plot rewrites × big</summary>
<img src="https://user-images.githubusercontent.com/8211902/154108736-88bbae5c-7b5a-4a5d-9c45-d10efb880ad5.png" alt="rewrites x big" style="max-width: 100%">
</details>

<details>
<summary>table</summary>
<table>
<tr><th>big</th><th>rewrites</th><tr>
<tr><td>0</td><td>13</td></tr>
<tr><td>200</td><td>65347</td></tr>
<tr><td>400</td><td>251996</td></tr>
<tr><td>600</td><td>550922</td></tr>
<tr><td>800</td><td>989813</td></tr>
<tr><td>1000</td><td>1671988</td></tr>
<tr><td>1200</td><td>2174371</td></tr>
<tr><td>1400</td><td>3110989</td></tr>
<tr><td>1600</td><td>3923598</td></tr>
<tr><td>1800</td><td>5163811</td></tr>
<tr><td>2000</td><td>6645709</td></tr>
<tr><td>2200</td><td>6904380</td></tr>
<tr><td>2400</td><td>8639676</td></tr>
<tr><td>2600</td><td>10257724</td></tr>
<tr><td>2800</td><td>12379622</td></tr>
<tr><td>3000</td><td>14579835</td></tr>
<tr><td>3200</td><td>15623847</td></tr>
<tr><td>3400</td><td>18160465</td></tr>
<tr><td>3600</td><td>20578236</td></tr>
<tr><td>3800</td><td>23500411</td></tr>
<tr><td>4000</td><td>26499302</td></tr>
<tr><td>4200</td><td>24189269</td></tr>
<tr><td>4400</td><td>27509205</td></tr>
<tr><td>4600</td><td>31071380</td></tr>
<tr><td>4800</td><td>34443989</td></tr>
</table>
</details>

It seems the rewrites grow quadratically with respect to `big`, not linearly. Perhaps this is related to #60? I'll run the tests again on the `quadratic_fix` branch and see if anything changes.

**Comment by LeoRiether** [comment]
Huh, I guess `let big = (double (inc (double zero))` doesn't work in `quadratic_fix`? It keeps reducing until it segfaults. (double, inc and zero are defined in [the script](https://gist.github.com/LeoRiether/ba6431429b976b6f814e12f594fca4c3))

Changing the representation  of big to `let big = λs λz (s (s (s ... (s z))))` fixes this segfault, but the runtime is still apparently quadratic, a bit worse than the other representation, and the number of rewrites doesn't change at all between `master` and `quadratic_fix`. (note: I'm not sure if this representation changes the complexity of `sub`...? hopefully my analysis is correct)

<details>
<summary>plot</summary>
<img src="https://user-images.githubusercontent.com/8211902/154120315-d2b5bf5c-d72f-44e3-a229-f5de8f6db449.png" alt="plot" style="max-width: 100%">
</details>

**Comment by VictorTaelin** [comment]
It could be related to that issue, yes. Probably is. I don't have the time to troubleshoot right now, but if anyone voluntaries, it is possible to trace the entire reduction with `hvm -d your_term` and manually inspect. This is very laborious, but can give us an insight on exactly where and why HVM is losing its asymptotic advantage. As I commented on the other thread, an easy fix would be to just add references, but that is also an extreme solution which would bring several disadvantages. Sadly Andrea Asperti didn't answer my question regarding this issue; I'd highly appreciate a clarification from a related researcher. HVM is just implementing the optimal evaluation algorithm, so, if this isn't a bug on HVM (which may be the case!), this program counts as a counter-example to its asymptotical optimality.

**Comment by VictorTaelin** [comment]
If I may ask, could you move this information to #60? This definitely should be on the pinned thread.
